# NAME: Gawun Kim
# EMAIL: gawun92@g.ucla.edu
# ID: 305186572

CC = gcc

default: 
	$(CC) -Wall -Wextra -g -o lab1a lab1a.c
all:
	$(CC) -Wall -Wextra -g -o lab1a lab1a.c
dist:
	tar -cvzf lab1a-305186572.tar.gz lab1a.c Makefile README 
clean:
	rm -f lab1a *.o *.tar.gz
