#NAME: GAWUN KIM
#EMAIL: gawun92@g.ucla.edu
#ID: 305186572

default: dist

dist: git.png connected.png build_run.png copy.png my_beaglebone.jpg README Makefile
	tar -czf lab4a-305186572.tar.gz git.png connected.png build_run.png copy.png my_beaglebone.jpg README Makefile
clean:
	rm -f lab4a-305186572.tar.gz
